#
# name: metta-run CI
#
# on:
#   push:
#     branches:
#       - main
#       - v0.3.0
#   pull_request:
#     branches:
#       - main
#       - v0.3.0
#
# jobs:
#   setup-and-test:
#     runs-on: ubuntu-latest
#
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-python@v5
#       with:
#         python-version: '3.11.6'
#
#     - name: install and setup metta-run script
#       run: |
#         curl -fsSL https://raw.githubusercontent.com/iCog-Labs-Dev/metta-prebuilt-binary/main/install.sh | bash
#
#     -name: install and setup metta
#       run: |
#
#     - name: Run tests
#       working-directory: ./
#       run: python3 scripts/run-tests.py
#
#     - name: Ensure metta-run is executable
#       run: chmod +x $HOME/metta-bin/metta-run
#
name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clone Hyperon Experimental Repository
      run: |
        git clone https://github.com/trueagi-io/hyperon-experimental.git

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip==23.1.2
        python -m pip install hyperon
        python -m pip install conan==2.5.0
        conan profile detect --force

    - name: Setup Rust Environment
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Verify Rust Installation
      run: rustc --version

    - name: Install cbindgen
      run: cargo install --force cbindgen

    - name: Build Project
      run: |
        cd hyperon-experimental
        python -m venv .env
        cargo build
        source .env/bin/activate

    - name: Run Tests
      working-directory: ./metta-attention
      run: |
          python scripts/run-tests.py

